def get_variation_category_choice():
    return (
        ('colour', 'colour'),
        ('size', 'size'),
        ('mapping', 'mapping'),
        ('air filter', 'air filter'),
        ('silicon hose colour', 'silicon hose colour'),
        ('intercooler', 'intercooler'),
        ('catalyst', 'catalyst'),
        ('GPF-Back Exhaust', 'GPF-Back Exhaust'),
        ('GPF Delete', 'GPF Delete'),
        ('Model Year Selection', 'Model Year Selection'),
        ('Turbo Exchange', 'Turbo Exchange'),
        ('Crackle on Overrun', 'Crackle on Overrun'),
        ('Booking Option', 'Booking Option'),
        ('Fuel Spec', 'Fuel Spec'),
        ('GPF Option', 'GPF Option'),
        ('Logo Choice', 'Logo Choice'),
        ('Turbo Exchange', 'Turbo Exchange'),
        ('Surcharge', 'Surcharge'),
        ('Tyre Selection', 'Tyre Selection'),
        ('TPMS Selection', 'TPMS Selection'),
        ('Fitting Selection', 'Fitting Selection'),
        ('Tyres', 'Tyres'),
        ('Quantity of Wheels', 'Quantity of Wheels'),
        ('Brake Pad', 'Brake Pad'),
        ('Brake Lines', 'Brake Lines'),
        ('Spacers (Front Axle)', 'Spacers (Front Axle)'),
        ('Add Tracklite Wheels', 'Add Tracklite Wheels'),
        ('Tuning Box Option', 'Tuning Box Option')
    )
