# Generated by Django 5.0.4 on 2024-04-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="description",
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
